### PR TITLE
Improve y-labels on instrumentation plots.

### LINKED ISSUE #50: Labels of instrumented plots overlap
The Right-hand side labels of instrumented plots can overlap and become unreadable if you have lots of instrumented plots for a benchmark. Either they need some dynamic font scaling or word wrapping or just a command line option to set the font size of the labels.

### PR DESCRIPTION
**Pull request by snim2**
This is a first go at better y-labels for instrumentation plots, here we apply word-wrapping. This may not be the best solution, but it avoids having a new CLI option.

I don't have great test data for this, so it would be helpful if someone else can give it a kicking. 

Fixes #50

### CODE REVIEW

**Comment by fsfod** [comment]
@snim2 it doesn't seem to be working or the max length needs to be shorter

**Comment by snim2** [comment]
Can you give me an example ylabel string?

**Comment by snim2** [comment]
OK, try that last commit

**Comment by snim2** [comment]
It really depends on how you want the ylabel to look like. If we replace the underscores with spaces then `textwrap` will prefer to wrap where there is whitespace. The alternative is to end up turning strings like `flibble_barfoo_bazarg` into `flibble_ba\nrfoo_bazarg` which makes the whole string more difficult to read.

If you have better solution then I'm happy to experiment a bit more.

**Comment by fsfod** [comment]
The only things i can think of is to implement a custom wrap function that would take in to account underscores and dots, or just record all the space locations and reconstruct separators after passing it through wrap but that seems terrible.

**Comment by snim2** [comment]
OK, let me have another look at this after lunch, there may be an easy way around it.

**Comment by snim2** [comment]
OK, I think this is more what you are looking for. However, it works really nicely on the examples you gave me, I suspect it won't always work so nicely, but the result should certainly be more readable.

**Comment by fsfod** [comment]
The new code works but i still get overlapping labels the the max line length might need to be a bit smaller or something

**Comment by snim2** [comment]
ok, this reduces the max length...

**Comment by snim2** [comment]
Note about progress on this (since we can't put all the test results on GH): this works OK with a few plots of instrumentation data, or without CC charts. With a larger stack of charts per pexec, the space between each chart is smaller and the y-labels begin to overlap again.

**Comment by snim2** [comment]
OK, this is a slightly different approach. Can you let me know how it works out on your examples? My number of test cases is limited!

screenshot from 2018-05-03 16-14-19

**Comment by snim2** [comment]
@fsfod did the last commit help?

**Comment by fsfod** [comment]
Well i'm still not a fan removing the underscore\dots from the names but i guess its better than before

**Comment by snim2** [comment]
Sadly, doing that way does not give good results, I've lowered the max number of characters a bit further in this screenshot and it still isn't very readable: 
screenshot from 2018-05-10 14-10-35

**Comment by fsfod** [comment]
I've also just been manually tweaking the font size of the labels each time to make it fit on top of your changes.

**Comment by snim2** [comment]
Do you find that readable? The label fonts are already very small.

**Comment by fsfod** [comment]
Well it depends i zoom in a bit as well

**Comment by snim2** [comment]
Well, I'm not necessarily against adding a CLI switch for it, if you think wrapping the text is not enough. Maybe @ltratt and @vext01 have some ideas / opinions?

**Comment by ltratt** [comment]
This is clearly never going to be able to be perfect: the user should expect that they might have to adjust their label name in order for things to render nicely. So I'm inclined to think this maybe does about a good a job as we can reasonably expect. I doubt we want to add a switch for this.

**Comment by snim2** [comment]
OK, @fsfod maybe we can squash now and if we think of anything clever later on we can make a separate PR?

For the GitHub record, I tried a couple of other things which didn't work. The one worth noting is that the spacing between each plot in the stack can be changed to move the plots further apart. This helps a little bit (not a lot) but it will likely cause the export size of each figure to change. This is something we set explicitly via a CLI option in the paper repo and in various presentations, so changing it is likely to have complicated consequences. :(

**Comment by fsfod** [comment]
Yeah just squash and maybe you could cherry pick the commit from my repo to add a explicit variable for right side label font size.

**Comment by snim2** [comment]
Ok, squashed!

**Pull request merged**
