### PR TITLE
Remove --with-changepoints.

### LINKED ISSUE #48: Can we remove --with-changepoints
The `--with-changepoints` switch was intended to provide a different view of changepoints - they would be marked with a blob at the bottom of the wallclock axis, rather than using the red vertical line and the horizontal lines (showing the segment mean) that `--with-changepoint-means` provides.

However, we have never yet used `--with-changepoints`, the switch it confusing for the user and the whole thing adds some unnecessary complexity to the code. Can we remove this?

/cc @ltratt @vext01 @fsfod

### PR DESCRIPTION
**Pull request by snim2**
This code used to plot changepoints as a black blob underneath the x-axis. It was never used in anger.

Fixes #48

### CODE REVIEW

**Comment by snim2** [comment]
Will need squashing (but Travis caught a real bug!)

**Comment by ltratt** [comment]
Looks good. Will need rebasing though.

**Comment by ltratt** [comment]
I think we can rebase this one now.

**Comment by snim2** [comment]
Squashed and rebased...

**Pull request merged**
