### PR TITLE
Improve look and feel of HTML tables.

### PR DESCRIPTION
**Pull request by snim2**
Add some padding to the left and right of table cells.
Fix vertical alignment in table cells.

Thanks to @ptersilie for the CSS!

### Old table
table-old

### New table
table-new

### Old diff
diff-old

### New diff
diff-new

### CODE REVIEW

**Comment by ltratt** [comment]
This looks very good to me.

One minor comment: we currently have bucketloads of whitespace in the CSS. Is it worth stripping some of this out at some point to reduce download times? And, yes, I know that worrying about this in 2018 is weird ;)

**Comment by snim2** [comment]
Ok, try that...

**Comment by ltratt** [comment]
Perfect. Merge as-is?

**Comment by snim2** [comment]
Let's squash that whitespace commit first I think

**Comment by ltratt** [comment]
OK, please squash.

**Comment by snim2** [comment]
Splat!

**Pull request merged**
