### PR TITLE
Work around Debian 8 pip.

### PR DESCRIPTION
**Pull request by vext01**
Work around Debian 8 pip.

Tested in isolation, now testing from top-level `build.sh`. Could take some time, as I accidentally blasted the wrong `work` dir...

Looks good?

### CODE REVIEW

**Comment by vext01** [comment]
Actually, I'm going to comment out the build of the VMs... bear with me.

**Comment by snim2** [comment]
Obviously, we are not supporting Ubuntu, but FYI on 17.10 `/etc/debian_version` says `stretch/sid` but the `pip` bit of `build.sh` seems to succeed.

**Comment by vext01** [comment]
Um, I didn't see that coming. Usually `/etc/debian_version` is a number.

I guess it's fine, as:
```
$ echo "stretch/sid" | cut -d. -f1
stretch/sid
```

Would not match `"8"`.

**Comment by snim2** [comment]
Is there another commit coming or is this one good to go?

**Comment by vext01** [comment]
The time (and thus the commit date) is wrong in the VM I am using. Is that an issue?

**Comment by snim2** [comment]
I doubt it, the commits are just a hash and a pointer in Git so if the metatdata is wonky I don't think it matters.

**Comment by vext01** [comment]
OK, well the top level build.sh worked with this, so merge when ready.

**Pull request merged**
