### PR TITLE
Fix bug in HotSpot instrumentation parser

### PR DESCRIPTION
**Pull request by snim2**

### CODE REVIEW

**Comment by vext01** [comment]
Looks good, let me test it.

**Comment by vext01** [comment]
Hah:
```
    print('Adding run sequence to %s %s' % key, machine)
TypeError: not enough arguments for format string
```

**Comment by vext01** [comment]
You need parens around `key, machine`

**Comment by snim2** [comment]
Yep, fix pushed

**Comment by vext01** [comment]
OK, squash away

**Comment by snim2** [comment]
Squashed

**Pull request merged**
