### PR TITLE
Optionally use longtable for LaTeX tables.

### PR DESCRIPTION
**Pull request by snim2**
LaTeX output before this PR: [long_before.pdf](https://github.com/softdevteam/warmup_stats/files/1376385/long_before.pdf)

and after: [long_after.pdf](https://github.com/softdevteam/warmup_stats/files/1376396/long_after.pdf)

### CODE REVIEW

**Comment by ltratt** [comment]
Is there any reason not to make this the default? Indeed, making it the only option? [I'm not a fan of command-line switches if we can do the right thing without them.]

**Comment by snim2** [comment]
It's a good question. We only really want it where we have a preamble (so, not when we generate tables to drop into a paper, I think). If we make that the only option, then we will also have to make a small change to the other table script in the other repo. What do you think?

**Comment by ltratt** [comment]
Agreed. Most of the time it's safe to assume people want a stand-alone PDF. So if we make `--without-preamble` a switch, then we can do the right thing most of the time. I don't know if this requires changing the other table script though -- the one in this repo seems the only one that's really going to be useful to users-who-aren't-us?

**Comment by snim2** [comment]
It is the one for people-who-aren't-us, but yes. OK, let me have a go at changing the script round, and I guess we want to lose the "not a longtable" option?

**Comment by ltratt** [comment]
Yeah, I think the default should be "add longtable preamble". Then a `--without-preamble` switch turns that off for people who want to dump the table into a paper.

**Comment by snim2** [comment]
The last commit tested OK. Good to squash?

**Comment by ltratt** [comment]
Yes please squash.

**Comment by snim2** [comment]
Squashed.

**Pull request merged**
