### PR TITLE
Build the same version of the R changepoint library we used in the past.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by vext01** [comment]
Are newer versions not usable then?

**Comment by vext01** [comment]
Right.

In the future we should try to update our deps, but (I guess?) not now.

**Comment by ltratt** [comment]
This stuff could do with a lot of love, but anything is better than nothing IMHO...

**Comment by vext01** [comment]
This isn't borsed :)

**Review by vext01 — APPROVED** [review]

**Pull request merged**
