### PR TITLE
More windows/WSL fixes

### PR DESCRIPTION
**Pull request by fsfod**
Switch to using devtools::install_git instead of devtools::install_github for the changepoint r module.
Added a gitignore for all compiled python filed generated and the work directories contents

### CODE REVIEW

**Comment by ltratt** [comment]
Trying a build now...

**Comment by ltratt** [comment]
OK, this seems to work well -- thanks!

Can you fix the grammar in the two commits messages? Once that's done, I think this is ready for merging.

**Comment by fsfod** [comment]
It would be nice to to have @snim2 opinion of my change because she changed the line before to fix something

**Comment by ltratt** [comment]
Sarah's away for a few days, but I've tried it out, so I'm happy.

**Comment by fsfod** [comment]
@ltratt  ready to merge

**Comment by ltratt** [comment]
Thanks!

**Pull request merged**
